---
title: "Wojan Ecography Special Issue Proposal"
format: docx
editor: visual
bibliography: references.bib
---

**Title:**

How do environmental parasite density and clustering interact to influence parasite burdens in host populations?

**Tentative Authors:**

Chris Wojan~1~ (wojan002\@umn.edu), Allison Shaw~1~ (ashaw\@umn.edu), Meggan Craft~1~ (craft004\@umn.edu)

1 - Department of Ecology, Evolution, and Behavior, University of Minnesota

**Article Type:**

Modeling Study

**Summary:**

[Background]{.underline}

Dynamical disease models often assume homogeneous disease exposure among hosts, but exposure to pathogens can be heterogeneous in time and space. While coarse-scale spatial heterogeneity in disease has been studied often (e.g., across landscapes or regions), fine-scale spatial dynamics are less examined (e.g., within habitat patches) [@albery2022]. Spatially heterogeneous disease exposure at the fine-scale can occur when there is variable spatial overlap between host and parasite, like in systems with multi-host, environmentally transmitted macroparasites. In these systems, the host of a parasite at one life stage can spatially decouple the parasite's distribution relative to the hosts of the subsequent life stage.

Spatial decoupling of parasites and hosts can lead to different parasite burdens compared to spatially coupled systems. For example, white-footed mice encounter larval *Ixodes scapularis* ticks based on where deer drop gravid adult females, not based on mouse space use. Mice then transmit Lyme disease and other pathogens to larvae, which determines the prevalence of diseases in nymphal ticks. Thus fine-scale spatial heterogeneity can alter the tick burdens experienced by hosts, tick population dynamics, and tick-borne pathogen prevalence. This is in contrast to disease systems where the spatial distributions of hosts and parasite/pathogen are more tightly linked (e.g., a single-host, directly transmitted virus).

[Aim]{.underline}

We use a modeling approach to describe how the abundance and clustering of parasites in the environment interact to influence the distribution of parasite burdens in host populations. Hosts infected with macroparasites typically vary in the magnitude of their burdens and the distribution of these burdens in a population is usually overdispersed (i.e., many hosts with very few parasites and few hosts with many parasites). For tick-borne disease, the basic reproductive number of pathogens increases with greater overdispersion of ticks on small mammal hosts [@harrison2012]. In the schistosomiasis system, symptoms in humans are associated with the magnitude of the worm burden [@colley2014]. It is likely that variable spatial exposure among hosts leads to parasite burdens of different magnitudes. We predict that clustered parasite arrangements will lead to overdispersed burden distributions, but the overdispersion will decrease with increasing parasite abundance.

[Methods]{.underline}

We explore these patterns with a system-agnostic spatially-explicit individual-based model. First we generate "parasite landscapes" with an algorithm that allows for modifying the number of parasites and the spatial autocorrelation of the parasite arrangement. Then we simulate movement of hosts on these landscapes with random walks, allowing for accumulation of parasites with exposure. Then we can measure how the dispersion (variance:mean ratio) changes with parasite abundance and clustering across many simulations. Preliminary results show an increase in burden dispersion with parasite clustering.

[Expected Outcomes]{.underline}

The results of this work will identify regions of parameter space for multi-host, environmental macro-parasites where homogeneous models may inaccurately capture dynamics. Applied to the Lyme disease system, the results may elucidate patterns of tick burdens on mice, for which studies have found conflicting explanations [@mowry2019]. Further, the complex dynamics of transmission heterogeneity in schistosomiasis [@mari2017] may also be informed by the work. This project will provide part of a theoretical foundation for examining disease drivers at a fine spatial scale - a scale which is often overlooked.

**Literature Cited:**
